# Generated by Django 2.2.6 on 2020-02-09 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dom',
            fields=[
                ('id_adr_dom', models.AutoField(primary_key=True, serialize=False)),
                ('numer_domu', models.CharField(max_length=10)),
                ('data_dod', models.DateTimeField(default=datetime.date.today)),
                ('data_mod', models.DateTimeField(default=datetime.date.today)),
                ('predkosc_max', models.FloatField(max_length=10, null=True)),
                ('licz_lokali', models.FloatField(max_length=10, null=True, verbose_name='Liczba lokali')),
            ],
        ),
        migrations.CreateModel(
            name='Gmina',
            fields=[
                ('id_adr_gmina', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_gminy', models.CharField(max_length=200)),
                ('nazdod', models.CharField(max_length=200)),
                ('nr_terytu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Handlowiec',
            fields=[
                ('id_um_podpisujacy', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('stanowisko', models.CharField(max_length=100)),
                ('aktywny', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kraj',
            fields=[
                ('id_adr_kraj', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_kraju', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Miejscowosc',
            fields=[
                ('id_adr_miejscowosc', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_miejscowosci', models.CharField(max_length=200)),
                ('nr_terytu', models.CharField(max_length=100)),
                ('nazwa_rm', models.CharField(max_length=100)),
                ('id_adr_gmina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Gmina', verbose_name='Gmina')),
            ],
        ),
        migrations.CreateModel(
            name='Sprzedawca',
            fields=[
                ('id_sprzedawca', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_sprzedawcy', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id_gniazdka_technologie', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id_adr_typ_budynku', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_typu', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wojewodztwo',
            fields=[
                ('id_adr_wojewodztwo', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_wojewodztwa', models.CharField(max_length=200)),
                ('nr_terytu', models.CharField(max_length=100)),
                ('id_adr_kraj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Kraj', verbose_name='Kraj')),
            ],
        ),
        migrations.CreateModel(
            name='Ulica',
            fields=[
                ('id_adr_ulica', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(max_length=100, null=True)),
                ('nazwa_ulicy_1', models.CharField(max_length=200, null=True)),
                ('nazwa_ulicy_2', models.CharField(max_length=200, null=True)),
                ('nazwa_ulicy', models.CharField(max_length=200, null=True)),
                ('nr_terytu', models.CharField(max_length=100, null=True)),
                ('id_adr_miejscowosc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Miejscowosc', verbose_name='Miejscowość')),
            ],
        ),
        migrations.CreateModel(
            name='Symbole',
            fields=[
                ('id_adr_dom_symbol', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('id_adr_dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Dom', verbose_name='Dom')),
                ('id_sprzedawca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sprzedawca', verbose_name='Sprzedawca')),
            ],
        ),
        migrations.CreateModel(
            name='Powiat',
            fields=[
                ('id_adr_powiat', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_powiatu', models.CharField(max_length=200)),
                ('nazdod', models.CharField(max_length=200)),
                ('nr_terytu', models.CharField(max_length=100)),
                ('id_adr_wojewodztwo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Wojewodztwo', verbose_name='Województwo')),
            ],
        ),
        migrations.CreateModel(
            name='Lokalizacja',
            fields=[
                ('id_adr_dom_podpisujacy', models.AutoField(primary_key=True, serialize=False)),
                ('id_adr_dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lokalizacja', to='core.Dom', verbose_name='Dom')),
                ('id_sprzedawca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sprzedawca', verbose_name='Sprzedawca')),
                ('id_um_podpisujacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Handlowiec', verbose_name='Handlowiec')),
            ],
        ),
        migrations.AddField(
            model_name='gmina',
            name='id_adr_powiat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Powiat', verbose_name='Powiat'),
        ),
        migrations.AddField(
            model_name='dom',
            name='id_adr_ulica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ulica', verbose_name='Ulica'),
        ),
        migrations.CreateModel(
            name='Budynek',
            fields=[
                ('id_adr_budynek', models.AutoField(primary_key=True, serialize=False)),
                ('numer_budynku', models.CharField(max_length=10)),
                ('opis_budynku', models.CharField(max_length=500, null=True)),
                ('id_adr_typ_budynku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Typ', verbose_name='Typ')),
                ('id_adr_ulica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ulica', verbose_name='Ulica')),
            ],
        ),
    ]
