# Generated by Django 2.2.6 on 2020-02-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dom',
            name='data_mod',
        ),
        migrations.RemoveField(
            model_name='dom',
            name='id_adr_ulica',
        ),
        migrations.AddField(
            model_name='dom',
            name='handlowiec',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='dom',
            name='ilosc_klientow',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dom',
            name='miejscowosc',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='dom',
            name='nazwa_ulicy',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='dom',
            name='symbol',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dom',
            name='technologia',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='dom',
            name='typ_budynku',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dom',
            name='uruchomienie',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dom',
            name='licz_lokali',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dom',
            name='numer_domu',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dom',
            name='predkosc_max',
            field=models.CharField(default='', max_length=10),
        ),
    ]
