# Generated by Django 2.2.4 on 2020-10-11 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulotki',
            name='uzytkownik',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ulica',
            name='id_adr_miejscowosc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Miejscowosc', verbose_name='Miejscowość'),
        ),
        migrations.AddField(
            model_name='symbole',
            name='id_adr_dom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Dom', verbose_name='Dom'),
        ),
        migrations.AddField(
            model_name='symbole',
            name='id_sprzedawca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sprzedawca', verbose_name='Sprzedawca'),
        ),
        migrations.AddField(
            model_name='probykontaktu',
            name='id_adr_dom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Dom', verbose_name='Dom'),
        ),
        migrations.AddField(
            model_name='probykontaktu',
            name='uzytkownik',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='powiat',
            name='id_adr_wojewodztwo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Wojewodztwo', verbose_name='Województwo'),
        ),
        migrations.AddField(
            model_name='photo',
            name='ulotki',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ulotki'),
        ),
        migrations.AddField(
            model_name='miejscowosc',
            name='id_adr_gmina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Gmina', verbose_name='Gmina'),
        ),
        migrations.AddField(
            model_name='lokalizacja',
            name='id_adr_dom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lokalizacja', to='core.Dom', verbose_name='Dom'),
        ),
        migrations.AddField(
            model_name='lokalizacja',
            name='id_sprzedawca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sprzedawca', verbose_name='Sprzedawca'),
        ),
        migrations.AddField(
            model_name='lokalizacja',
            name='id_um_podpisujacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Handlowiec', verbose_name='Handlowiec'),
        ),
        migrations.AddField(
            model_name='lokalehistory',
            name='id_adr_dom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Dom', verbose_name='Dom'),
        ),
        migrations.AddField(
            model_name='lokalehistory',
            name='id_adr_lokal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Lokale'),
        ),
        migrations.AddField(
            model_name='lokalehistory',
            name='konkurencja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Konkurencja'),
        ),
        migrations.AddField(
            model_name='lokalehistory',
            name='uzytkownik',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lokale',
            name='id_adr_dom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Dom', verbose_name='Dom'),
        ),
        migrations.AddField(
            model_name='lokale',
            name='konkurencja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Konkurencja'),
        ),
        migrations.AddField(
            model_name='lokale',
            name='uzytkownik',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instalacjezdjecia',
            name='instalacje',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Instalacje'),
        ),
        migrations.AddField(
            model_name='instalacje',
            name='uzytkownik',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gmina',
            name='id_adr_powiat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Powiat', verbose_name='Powiat'),
        ),
        migrations.AddField(
            model_name='dom',
            name='jaka_konkurencja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Konkurencja'),
        ),
        migrations.AddField(
            model_name='budynek',
            name='id_adr_typ_budynku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Typ', verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='budynek',
            name='id_adr_ulica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ulica', verbose_name='Ulica'),
        ),
    ]
