# Generated by Django 2.2.4 on 2020-10-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201011_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='dom',
            name='nazwa_gminy',
            field=models.CharField(default='', max_length=100),
        ),
    ]
