# Generated by Django 2.2.6 on 2020-02-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200226_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='uruchomienie',
            field=models.DateField(),
        ),
    ]
