# Generated by Django 2.2.4 on 2020-10-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dom_nazwa_gminy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dom',
            name='ilosc_klientow',
        ),
    ]
