# Generated by Django 2.2.4 on 2020-10-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_dom_ilosc_klientow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='predkosc_max',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
