# Generated by Django 2.2.4 on 2020-10-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201017_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='nazwa_ulicy',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
