# Generated by Django 2.2.6 on 2020-02-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200228_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dom',
            name='uruchomienie',
        ),
    ]
