# Generated by Django 2.2.4 on 2020-10-18 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20201017_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gminy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_gminy', models.CharField(default='', max_length=30)),
                ('ulotkarz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
