# Generated by Django 2.2.4 on 2020-11-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gminy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dom',
            name='jaka_konkurencja',
        ),
        migrations.AddField(
            model_name='dom',
            name='jaka_konkurencja',
            field=models.ManyToManyField(related_name='konkurencje', related_query_name='konkurencje', to='core.Konkurencja'),
        ),
        migrations.AlterField(
            model_name='gminy',
            name='nazwa_gminy',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
