# Generated by Django 2.2.6 on 2020-02-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200228_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='nazwa_ulicy',
            field=models.CharField(default='', max_length=50),
        ),
    ]
