# Generated by Django 2.2.4 on 2022-02-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201123_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='dom',
            name='opis_budynku',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
