# Generated by Django 2.2.4 on 2022-02-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dom_opis_budynku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='opis_budynku',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
