# Generated by Django 2.2.6 on 2020-02-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200228_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokale',
            name='konkurencji_klient',
            field=models.BooleanField(default=False),
        ),
    ]
