# Generated by Django 2.2.6 on 2020-02-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_lokale_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokale',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
