# Generated by Django 2.2.6 on 2020-02-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_lokale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokale',
            name='data_dodania_wpisu',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lokale',
            name='data_modyfikacji',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='lokale',
            name='price',
            field=models.FloatField(null=True, verbose_name='Obecnie płaci'),
        ),
    ]
