# Generated by Django 2.2.6 on 2020-02-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200228_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='RodzajKontaktu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_kontaktu', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
