# Generated by Django 2.2.6 on 2020-02-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rodzajkontaktu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokale',
            name='data_kontaktu',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
