# Generated by Django 2.2.6 on 2020-02-28 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200228_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='LokaleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_mieszkania', models.IntegerField()),
                ('nasz_klient', models.BooleanField(default=False)),
                ('konkurencji_klient', models.BooleanField(default=False)),
                ('data_kontaktu', models.DateTimeField(blank=True, null=True)),
                ('data_konca_umowy', models.DateField(blank=True, null=True)),
                ('data_kolejnego_kontaktu', models.DateField(blank=True, null=True)),
                ('klatka', models.CharField(blank=True, default='', max_length=10)),
                ('uzytkownik', models.CharField(blank=True, max_length=50)),
                ('data_dodania_wpisu', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True, null=True)),
                ('rodzaj_kontaktu', models.CharField(blank=True, default='', max_length=100)),
                ('opis', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Obecnie płaci')),
                ('id_adr_dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Dom', verbose_name='Dom')),
                ('konkurencja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Konkurencja')),
            ],
        ),
    ]
