# Generated by Django 2.2.6 on 2020-02-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_lokalehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokalehistory',
            name='id_adr_lokal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Lokale'),
        ),
    ]
