# Generated by Django 2.2.6 on 2020-03-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_lokalehistory_id_adr_lokal'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokale',
            name='imie_klienta',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lokale',
            name='telefon',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
