# Generated by Django 2.2.6 on 2020-03-01 17:48

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200301_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ulotki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, upload_to='Ulotki/%Y/%m/%d', validators=[core.models.my_validate])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('opis', models.CharField(default='', max_length=300)),
                ('id_adr_dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Dom', verbose_name='Dom')),
            ],
        ),
    ]
