# Generated by Django 2.2.6 on 2020-03-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200302_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulotki',
            name='uzytkownik',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
