# Generated by Django 2.2.6 on 2020-03-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_ulotki_uzytkownik'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokalehistory',
            name='imie_klienta',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lokalehistory',
            name='telefon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
