# Generated by Django 2.2.6 on 2020-03-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200302_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokale',
            name='imie_klienta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lokalehistory',
            name='imie_klienta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
