# Generated by Django 2.2.6 on 2020-03-04 21:04

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200302_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ulotki',
            name='file',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, upload_to='Ulotki/%Y/%m/%d', validators=[core.models.my_validate])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ident', models.IntegerField(default=None, null=True)),
                ('ulotki', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ulotki')),
            ],
        ),
    ]
