# Generated by Django 2.2.6 on 2020-03-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200304_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='ident',
        ),
    ]
