# Generated by Django 2.2.6 on 2020-03-07 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_remove_photo_ident'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbyKontaktu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_mieszkania', models.IntegerField()),
                ('data_proby_kontaktu', models.DateTimeField(auto_now_add=True)),
                ('id_adr_dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Dom', verbose_name='Dom')),
                ('uzytkownik', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
