# Generated by Django 2.2.6 on 2020-03-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_instalacje_instalacjezdjecia'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacjezdjecia',
            name='ident',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
